language: java
jdk:
    - openjdk11

cache:
    directories:
        - .git/lfs
git:
    lfs_skip_smudge: true

install:
    - git lfs pull

before_install:
    grep -v '^#' assets/src/main/resources/META-INF/services/bisq.asset.Asset | sort --check --dictionary-order --ignore-case
